name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_swiper_view: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  easy_refresh: ^3.3.1
  dio: ^5.4.3
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
